### ISSUE TITLE
Photo credits, description for hourly updates missing

### ISSUE THREAD

**Issue by Efreak** [Thunder07/-XPOSED-MOD-Zeus-Contextual-Expanded-Status-Header#11]
The in-app photo credits link doesn't do anything when tapped; it doesn't even highlight. I was thinking that maybe it's missing href or formatted placeholder, but a look at the source shows that's not true, so I'm not sure what's happening there. There should probably at least be a link to the file on the GitHub description, as the alternative is digging through the repo to find it.

Also, there's no description anywhere of what exactly the hourly updates does, either in the app or in GitHub.

**Comment by Zer0xFF** [comment]
Hi Efreak,
I thought the hourly update was self evident I didn't bother explaining it,
simply put, the morning picture will change on an hourly pace instead of it being set 1 time it's set at the start of the morning.. and thats true for the afternoon, evening and night time.

I've had a quick look at the app and you're right the photo credit link it's working correctly, if I had to guess, the textview above it, is extending down, prevent the click, once I get the chance, I'll confirm and fix it, thanks.
